# -*- coding: utf-8 -*-
"""p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svyWY4bBuyihACb_Blh-dPpN_6ZjfFzm
"""

# nama file p1.py 
# Isikan nama anda dan copy semua cell code yang dengan komentar #Graded
 
priority = 1

#netacad email cth: 'abcd@gmail.com'
email='raspianiyani@gmail.com'
 
# copy-paste semua #Graded cells YANG SUDAH ANDA KERJAKAN di bawah ini

#No.1
#Graded

def letter_catalog(items,letter='A'):
  pass
  # MULAI KODEMU DI SINI
  return [item for item in items if item[0] == letter]

#No.2
#Graded

def counter_item(items):
  pass
  # MULAI KODEMU DI SINI
  return dict((i, items.count(i)) for i in items)

#No.3
#Graded

# dua variable berikut jangan diubah
fruits = ['Apple','Avocado','Banana','Blackberries','Blueberries','Cherries','Date Fruit','Grapes','Guava','Jackfruit','Kiwifruit']
prices = [6,5,3,10,12,7,14,15,8,7,9]

# list buah
chart = ['Blueberries','Blueberries','Grapes','Apple','Apple','Apple','Blueberries','Guava','Jackfruit','Blueberries','Jackfruit']

# MULAI KODEMU DI SINI
fruit_price = dict(zip(fruits, prices))

#fruit_price = None

def total_price(dcounter,fprice):
  pass
  # MULAI KODEMU DI SINI
  total = [fprice[key] * dcounter[key] for key in dcounter.keys()]
  total = sum(total)
  return total

#No.4
#Graded

def discounted_price(total,discount,minprice=100):
  pass
  # MULAI KODEMU DI SINI
  if total >= minprice:
    diskon = total * discount / 100
    harga_total = total - diskon
    return(harga_total)
  else:
    return(total)

#No.5
#Graded

def print_summary(items,fprice):
  pass
  # MULAI KODEMU DI SINI
  daftar_buah = counter_item(items)
  for namabuah, jumlahbuah in sorted(daftar_buah.items()):
    totalhargabuah = fprice[namabuah] * daftar_buah[namabuah]
    print("{} {} : {}".format(jumlahbuah, namabuah, totalhargabuah))
  total = total_price(daftar_buah,fprice)
  print("total : {}".format(total))
  diskon = discounted_price(total,discount=10,minprice=100)
  print("discount price : {}".format(diskon))